<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="F_TURBO_PROT_SLND_ILK" Id="{7e98807e-1324-4a17-9e6c-4b80757f2756}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_TURBO_PROT_SLND_ILK : BOOL
VAR_INPUT
    i_Turbo : ST_PTM; // Turbo Pump
	i_stISG : ST_VG; //Gauge measuring inlet Pressure e.g Pirani
	i_stBSG : ST_VG; //Gauge measuring backing Pressure e.g Pirani
	ScrollPump : ST_RoughPump; // Roughing pump
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_TURBO_PROT_SLND_ILK := (i_stISG.xPRESS_OK AND i_stISG.rPRESS < i_Turbo.rInletPressureSP)
						    AND (i_stBSG.xPRESS_OK AND i_stBSG.rPRESS < i_Turbo.rBackingPressureSP)
                            AND (ScrollPump.eState = pumpRUNNING)
							AND (i_Turbo.eState = pumpRUNNING);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>