<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="F_TURBO_PROT_SLND_ILK" Id="{7e98807e-1324-4a17-9e6c-4b80757f2756}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_TURBO_PROT_SLND_ILK : BOOL
VAR_INPUT
	ScrollPump : ST_RoughPump;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_TURBO_PROT_SLND_ILK := ScrollPump.eState = pumpRUNNING;]]></ST>
    </Implementation>
    <LineIds Name="F_TURBO_PROT_SLND_ILK">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>